include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true           # Evitar uso de print
    prefer_final_locals: true   # Use variáveis locais final sempre que possível
    always_declare_return_types: true  # Sempre declare o tipo de retorno
    unnecessary_this: true      # Remova o uso desnecessário de "this"
    prefer_const_constructors: true  # Prefira construtores const quando possível
    always_put_required_named_parameters_first: true
    avoid_final_parameters: true
    
